### ISSUE TITLE
Maven failed to resolve geotoolkit dependency.

### ISSUE THREAD

**Issue by keshavnangare** [Geomatys/geotoolkit#11]
We have geotoolkit dependency in our project and build failed with the following errors.
`mvn clean install` failed

`[ERROR] Failed to execute goal on project xxx-project: Could not resolve dependencies for project xxx-project:jar:1.2-SNAPSHOT: The following artifacts could not be resolved: org.geotoolkit.pending:geotk-xml-gml:jar:3.21.1, org.geotoolkit.pending:geotk-jtswrapper:jar:3.21.1, org.geotoolkit:geotk-epsg:jar:3.21.1: Could not find artifact org.geotoolkit.pending:geotk-xml-gml:jar:3.21.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

Also I have configured the repository in my pom.xml

```
 <repositories>
    <!-- Geotk 3.21 not available in Central repository -->
    <repository>
      <id>geotoolkit</id>
      <name>Geotk Modules</name>
      <url>http://maven.geotoolkit.org/</url>
      <layout>default</layout>
    </repository>
  </repositories>
```

Anyone can help me with this issue?

Thank you!!

**Comment by desruisseaux** [comment]
Hello. This is caused by an error in or DNS setting. We are in process of fixing it. You can either wait a few hours for the DNS change to propagate, or replace maven.geotoolkit.org by https://nexus.geomatys.com/repository/geotoolkit/ for now.

**Comment by keshav-nangare** [comment]
@desruisseaux Thank you!!

We will wait for DNS change.

**Comment by keshav-nangare** [comment]
Thank you @desruisseaux.

**Comment by azrinsani** [comment]
Hi, this is still not working, Maven is still not resolving this:

`        <dependency>
            <groupId>org.geotoolkit</groupId>
            <artifactId>referencing</artifactId>
            <version>3.20-geoapi-3.0</version>
        </dependency>`

**Comment by desruisseaux** [comment]
Hello. Could you confirm if the following works?

https://maven.geotoolkit.org/org/geotoolkit/referencing/3.20/referencing-3.20.pom

It redirects to another server, but you should see the file content.
