### ISSUE TITLE
Maven site down

### ISSUE THREAD

**Issue by bmoffett42** [Geomatys/geotoolkit#17]
Requests to http://maven.geotoolkit.org are timing out, can't resolve artifacts

**Comment by desruisseaux** [comment]
Yes, there is a power outage in the building where is located the server. It affects the whole area, there is nothing we can do by ourselves. We have been told that electricity will be restored tomorrow (Thursday) at best.

**Comment by desruisseaux** [comment]
We have been told that electricity may be back in one more day (Friday).

**Comment by desruisseaux** [comment]
Electricity will be back Tuesday at best. It will be almost one full week for that electricity company to restore power…

**Comment by desruisseaux** [comment]
Power has been restored and http://maven.geotoolkit.org is back online. Sorry for the inconvenience.
