### ISSUE TITLE
License Issue on geotk-feature-h2 module

### ISSUE THREAD

**Issue by nicolas-f** [Geomatys/geotoolkit#3]
Hi,

We are pleased to see that you use H2GIS. However there is an important issue:

The projects `h2spatial`, `h2spatial-api`, `spatial-utilities`, `cts` are under GNU General Public License (GPLV3+) license.
http://www.geotoolkit.org/modules/storage/geotk-feature-h2/dependencies.html

Projects that depends on H2GIS can't be licensed under the LGPL. You have to re-license your project under GPL V3 in order to comply with H2GIS's license.

Regards,

-- 
Nicolas Fortin
IRSTV FR CNRS 2488
GIS        http://orbisgis.org
Spatial DB http://h2gis.org
Noise      http://noisemap.orbisgis.org

**Comment by vheurteaux** [comment]
Hello Nicolas,

Thank’s for pointing this issue, H2GIS has been integrated by mistake on the Geotk trunk, sorry for that.
It was initially used on an external GPL project and the developer in charge of the developments integrated it on Geotk trunk for commodity reasons.

We’re removing it right now.

Regards,

-----
Vincent HEURTEAUX
PDG - Geomatys SAS
http://www.geomatys.com

**Comment by nicolas-f** [comment]
Its fixed, thank you.

**Comment by ebocher** [comment]
Hey Vincent,

Glad to known that Geomatys is using H2GIS. A bit curious about the external GPL project ?

Cheers

Erwan
