### ISSUE TITLE
JavaDocs are down

### ISSUE THREAD

**Issue by Brideau** [Geomatys/geotoolkit#9]
Just letting you know that the JavaDocs linked from the main web page are showing the Apache HTTP Server Test Page: http://javadoc.geotoolkit.org/

![screenshot-2017-11-27 apache http server test page powered by centos](https://user-images.githubusercontent.com/844397/33275093-f4a1255a-d35f-11e7-9cde-237096ad0c0f.png)

**Comment by desruisseaux** [comment]
Thank you very much for letting us know. We will take this opportunity for upgrading our system. The work is underway, hopefully javadoc, Jenkins and the rest will be back tomorrow.

**Comment by desruisseaux** [comment]
http://javadoc.geotoolkit.org/ is back but not yet updated to latest code. We are still working on it.
